/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import static org.junit.Assert.assertEquals;


import org.junit.Test;

public class AppTest {
   @Test 
    public void testeCriacaoAluno() {
        // Testa se conseguimos instanciar um aluno e atribuir um nome
        Aluno aluno = new Aluno();
        aluno.setNome("Gustavo");
        assertEquals("Gustavo", aluno.getNome());
    }
}
